/**
 * Vercel Serverless Function Entry Point
 *
 * The vercel-build step bundles src/ into api/_server.js
 * This file imports from that bundle so Vercel can serve it.
 */

// @ts-ignore - _server.js is generated by vercel-build
import { createServerlessHandler } from "./_server.js"

const API_KEY = process.env.API_KEY

if (!API_KEY) {
  throw new Error("API_KEY environment variable is required")
}

let handler: ((req: Request) => Promise<Response>) | undefined

export default async function (req: Request): Promise<Response> {
  if (!handler) {
    handler = await createServerlessHandler(API_KEY)
  }
  return handler!(req)
}
